### ISSUE TITLE
Error page UI

### ISSUE THREAD

**Issue by adrianwithah** [justincqz/orbit-db-time-machine#24]
- [ ] Have a 404 page

**Comment by hannessolo** [comment]
Is error UI really a priority? We already have an error message for invalid database addresses and timeouts...

**Comment by adrianwithah** [comment]
The UI itself isn't a priority, but I think the error handling should be. Split into 2 bullet points

**Comment by hannessolo** [comment]
But don't we already have the error handling? What errors haven't we handled yet?

**Comment by adrianwithah** [comment]
off the top of my head, bad routes is one example. Also the following code path:
![image](https://user-images.githubusercontent.com/20010384/66830078-8df97680-ef4c-11e9-85e0-cdb51fbe867c.png)

We probably want to show somehow that fetching the data failed (so we don't have to do console debugging in the future)

**Comment by hannessolo** [comment]
The error handling in your screenshot is already done, if there is an error thrown, it will be displayed to the user on the page

**Comment by adrianwithah** [comment]
I'll scope it to just the 404, it can be something simple with a link back to the homepage. I can do that.
